---
name: Compliance tests
        
on:
  push:
    branches:
      - main
  workflow_dispatch:
    
    
jobs:
  test-compliance:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.CODEQL_APP_ID }}
          private-key: ${{ secrets.CODEQL_TEST }}
          owner: ${{ github.repository_owner }}      
    
        
