---
name: Compliance tests
        
on:
  push:
    branches:
      - main
  workflow_dispatch:
    
    
jobs:
  test-compliance:
    runs-on: ubuntu-latest
    steps:

      - name: Generate GitHub token
        id: generate-token
        uses: getsentry/action-github-app-token@v3
        with:
          app_id: ${{ secrets.CODEQL_APP_ID }}
          private_key: ${{ secrets.CODEQL_AUTHENTICATION_PRIVATE_KEY }}

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.CODEQL_APP_ID }}
          private-key: ${{ secrets.CODEQL_AUTHENTICATION_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}      
    
        
